### ISSUE TITLE
Code missing

### ISSUE THREAD

**Issue by joemerlino** [loganoconnell/Falcon#1]
Hi

just wanna know if this is the entire tweak or just a part of it.

I'm on 9.3.3 and installing the deb file I found here, my devices go in safe mode (correctly since the tweak is designed for iOS 10).

But if I compile the tweak on my own, I can see it from settings but looks like it's just the preference panel.

Thanks in advance.

**Comment by loganoconnell** [comment]
This is the entire tweak, it definitely will not function though on iOS 9.3.3, so I have no clue how you would fare installing it on that version.

**Comment by joemerlino** [comment]
Thanks for the fast reply,

Just wanna try to make it compatible with 9.3.3, I did install it to see the difference between your precompiled version and the one I compiled myself using the code in this repo.

Again, seems strange that the version I compiled myself doesn't send the device in safe mode so I was wondering if there's something missing from the code you posted.

Thanks!

**Comment by loganoconnell** [comment]
If you compile it yourself, you'll need to comment our the DRM at the top of the FalconLS.xm file. To make it compatible with iOS 9.3.3, I would check out the Lock Pages package, as all you would have to do is transfer the views I created on iOS 10 to Lock Pages on iOS 9. If you are porting it for iOS 9, thank you, I appreciate the effort. Let me know if you have any questions or need me to help.
